//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDisco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int IdCancion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Duracion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
