//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDisco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Album = new HashSet<Album>();
            this.Cancion = new HashSet<Cancion>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public short Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaActivacion { get; set; }
        public string CodigoActivacion { get; set; }
    
        public virtual ICollection<Album> Album { get; set; }
        public virtual ICollection<Cancion> Cancion { get; set; }
    }
}
